eureka:
  client:
    service-url:
      defaultZone: hppt://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "+"
  info:
    env:
      enabled: true
  endpoits:
    info:
      enabled: true
